### ISSUE TITLE
onDiscard触发问题

### ISSUE THREAD

**Issue by oathll** [theajack/logger#3]
将max设置为10后测试onDiscard的回调值，但是始终没有触发，版本是0.0.3

**Comment by theajack** [comment]
感谢反馈 我看一下这个

**Comment by oathll** [comment]
> 感谢反馈 我看一下这个
  private _onMessage (data: IWorkerBackMessage) {
    if (data.type === 'add') {
      const result = data.result;
      if (result) {
        if (result.__type === 'discard') {  //  这判断进不去的，改一下就好
          if (this.onReport) this.onReport(result?.add as ILogDBData);
          if (this.onDiscard) this.onDiscard(result?.discard as ILogDBData);
        } else {
          if (this.onReport) { this.onReport(result as ILogDBData);}
        }
      }
    }

**Comment by theajack** [comment]
我这边使用下来是正常的呢 可以正确的触发 你这边是这样使用的吗 @oathll 

<img width="338" alt="image" src="https://user-images.githubusercontent.com/23377279/205344027-782d5510-6af4-448e-a959-b6cf62270f0d.png">

<img width="961" alt="image" src="https://user-images.githubusercontent.com/23377279/205344176-6eb663e0-410a-40d6-9326-5b49a89ce953.png">

**Comment by theajack** [comment]
已修复 请升级到0.0.4使用
