### ISSUE TITLE
react 项目中报错：Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'transaction')

### ISSUE THREAD

**Issue by tAQiAN** [theajack/logger#4]
```
import Logger from 'idb-logger'

const logger = new Logger()

async function _log(){
  console.log((await logger.log('test'))?.add);
}

_log()
logger.download()
```
我在一个react 项目中使用，下载日志的时候会报Cannot read properties of undefined (reading 'transaction')
两种引入方法都尝试使用过，报同一种错误。
有点儿不太清楚哪方面出问题了。。。。

**Comment by theajack** [comment]
使用的浏览器型号和版本号发一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月24日(周五) 中午11:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [theajack/logger] react 项目中报错：Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'transaction') (Issue #4)




 
import Logger from 'idb-logger'
 
const logger = new Logger()
 
async function _log(){
 console.log((await logger.log('test'))?.add);
 }
 
_log()
 logger.download()

**Comment by tAQiAN** [comment]
![image](https://user-images.githubusercontent.com/46029320/227423544-54e06858-c07b-4f35-b3d6-a99d03603ca9.png)
react：17.0.0
不知道有没有影响，我这是一个桌面应用，electron：19.0.0

**Comment by theajack** [comment]
在 electron中使用，要保证 new Logger 的操作是在浏览器环境中执行的。而不是在node环境中
