### ISSUE TITLE
冗余信息太多

### ISSUE THREAD

**Issue by CaiWenlie** [theajack/logger#5]
每一条log都记录了ua, uid等信息，能否精简一下

**Comment by theajack** [comment]
@CaiWenlie 这里之前主要考虑的是希望每条日志都可以有完整的信息 可以下个版本考虑看看怎么优化

**Comment by theajack** [comment]
由于ua、id、url等信息其实都是可变的，所以这里暂时不考虑对冗余信息进行复用或者压缩
